/*
 * Copyright (c) 2026 Joseph Kulig.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Created: 2026-09-21
 */
package java.security;

/**
 * The service-provider interface for {@link SecureRandom}.
 *
 * <p>OVERLAID for the same reason {@link SecureRandom} is: stock's version is declared in terms of
 * {@code SecureRandomParameters} and the SP 800-90A {@code engineReseed}/{@code engineGetParameters}
 * surface, which belongs to the pluggable-provider machinery this VM does not carry. The three methods
 * below are the classic contract, and they are the ones an ordinary implementation overrides.
 */
public abstract class SecureRandomSpi implements java.io.Serializable
{
    /**
     * Reseed this generator. Stock SUPPLEMENTS rather than replaces, and an implementation here must do the
     * same: a {@code setSeed} that RESET the state would let a caller who supplies a guessable seed erase
     * whatever real entropy the generator already held.
     *
     * @param seed the seed material
     */
    protected abstract void engineSetSeed(byte[] seed);

    /**
     * Fill {@code bytes} with generated bytes.
     *
     * @param bytes the buffer to fill
     */
    protected abstract void engineNextBytes(byte[] bytes);

    /**
     * {@return {@code numBytes} of SEED material} This is the entropy source itself, not the generator, so
     * an implementation that has no source must fail here rather than return generated bytes -- handing
     * back the generator's own output would let a caller reseed it from itself, which adds nothing and
     * looks like it added everything.
     *
     * @param numBytes how many bytes of seed are wanted
     */
    protected abstract byte[] engineGenerateSeed(int numBytes);
}
