/*
 * Copyright (c) 2026 Joseph Kulig.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Created: 2026-09-21
 */
package crypto;

/**
 * The SHA1PRNG deterministic random bit generator -- the engine behind
 * {@code java.security.SecureRandom} on this VM.
 *
 * <p>This is the SUN provider's algorithm, reproduced exactly: a 20-byte state, and
 * {@code output(n) = SHA-1(state(n))} with {@code state(n+1) = (state(n) + output(n) + 1) mod 2^160}, plus a
 * remainder buffer so a draw that is not a multiple of 20 bytes carries the unused tail into the next call.
 *
 * <p>WHY THIS ALGORITHM, AND IT IS A TESTABILITY ARGUMENT RATHER THAN A CRYPTOGRAPHIC ONE. A DRBG is the
 * worst possible place for a from-memory implementation: every output looks equally random, so a
 * subtly-wrong one is not detectable by inspection, by a statistical test, or by any demo. What makes this
 * algorithm safe to write here is that the JDK ships it and it is DETERMINISTIC from {@code setSeed} -- so
 * {@code hosttest.CryptoTest} can put this side by side with the JDK's own and compare byte for byte, over
 * many seeds, ragged draw lengths and mid-stream reseeds. That is a known-answer gate, and no other
 * generator available to this project has one. (SP 800-90A's Hash_DRBG would be the better modern choice;
 * its CAVP vectors are not in this tree, and writing a DRBG against vectors recalled from memory is exactly
 * the silent wrong answer this note exists to avoid.)
 *
 * <p>SEEDING IS THE CALLER'S PROBLEM AND THIS CLASS DOES NOT PRETEND OTHERWISE. It has no entropy source of
 * its own: {@link #Sha1Prng(byte[], int)} demands seed material. A DRBG with a guessable seed produces a
 * guessable stream however good the algorithm is, so the decision about where seed bytes come from belongs
 * to {@code java.security.SecureRandom}, which states plainly what this VM can and cannot supply.
 *
 * <p>Strictly JDK-free (primitive arrays + int math), so the same source runs on the seed JVM under
 * CryptoTest and compiles into the bare-metal image.
 */
public final class Sha1Prng
{
    private static final int DIGEST = 20;

    private final Digest md = new Digest(Digest.SHA1);
    private final byte[] state = new byte[DIGEST];
    private byte[] remainder = new byte[DIGEST];
    private int remCount;

    /**
     * A generator seeded with {@code seed[0..len)}.
     *
     * @param seed seed material
     * @param len  how much of it to use
     */
    public Sha1Prng(byte[] seed, int len)
    {
        md.update(seed, 0, len);
        byte[] first = md.digest();
        int i = 0;
        while (i < DIGEST)
        {
            state[i] = first[i];
            i = i + 1;
        }
        remCount = 0;
    }

    /**
     * MIX more seed material in. Stock's {@code setSeed} supplements rather than replaces -- the new state
     * is {@code SHA-1(oldState || seed)} -- so seeding again can only add uncertainty, never reset the
     * generator to a state an attacker who knows only the new seed could predict.
     *
     * @param seed seed material
     * @param len  how much of it to use
     */
    public void setSeed(byte[] seed, int len)
    {
        md.update(state, 0, DIGEST);
        int i = 0;
        while (i < DIGEST)
        {
            state[i] = 0;
            i = i + 1;
        }
        md.update(seed, 0, len);
        byte[] next = md.digest();
        i = 0;
        while (i < DIGEST)
        {
            state[i] = next[i];
            i = i + 1;
        }
        remCount = 0;
    }

    /**
     * Advance the state: {@code state = (state + output + 1) mod 2^160}, little-endian byte order with the
     * carry running upward from index 0.
     *
     * <p>The {@code changed} check is stock's and is not decoration: if the addition left every byte of the
     * state identical -- which the modular sum can do -- the generator would emit the same block for ever.
     * Bumping one byte guarantees forward progress.
     */
    private static void updateState(byte[] state, byte[] output)
    {
        int last = 1;
        boolean changed = false;
        int i = 0;
        while (i < DIGEST)
        {
            int v = (int) state[i] + (int) output[i] + last;
            byte t = (byte) v;
            if (state[i] != t)
            {
                changed = true;
            }
            state[i] = t;
            last = v >> 8;
            i = i + 1;
        }
        if (!changed)
        {
            state[0] = (byte) (state[0] + 1);
        }
    }

    /**
     * Fill {@code out[off..off+len)} with generated bytes.
     *
     * <p>The remainder buffer is what makes a ragged draw agree with the JDK: a 5-byte request consumes 5
     * bytes of a 20-byte block and the next request continues from byte 5 rather than generating a fresh
     * block. Consumed bytes are ZEROED as they are handed out, as stock does, so the buffer never holds
     * output that has already been given away.
     *
     * @param out where to write
     * @param off where in {@code out}
     * @param len how many bytes
     */
    public void nextBytes(byte[] out, int off, int len)
    {
        int index = 0;
        byte[] output = remainder;
        int r = remCount;
        if (r > 0)
        {
            int todo = (len - index) < (DIGEST - r) ? (len - index) : (DIGEST - r);
            int i = 0;
            while (i < todo)
            {
                out[off + i] = output[r];
                output[r] = 0;
                r = r + 1;
                i = i + 1;
            }
            remCount = remCount + todo;
            index = index + todo;
        }
        while (index < len)
        {
            md.update(state, 0, DIGEST);
            output = md.digest();
            updateState(state, output);
            int todo = (len - index) > DIGEST ? DIGEST : len - index;
            int i = 0;
            while (i < todo)
            {
                out[off + index] = output[i];
                output[i] = 0;
                index = index + 1;
                i = i + 1;
            }
            remCount = remCount + todo;
        }
        remainder = output;
        remCount = remCount % DIGEST;
    }
}
